
import javax.swing.JOptionPane;


public class hotelForm extends javax.swing.JFrame {
    
    private Hotel hotel;
    
    public hotelForm() {
        initComponents();
        hotel = new Hotel();
        radioVacaciones.setSelected(true);
        chkConferencia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNrohabitacion = new javax.swing.JTextField();
        txtReservados = new javax.swing.JTextField();
        chkVigente = new javax.swing.JCheckBox();
        radioVacaciones = new javax.swing.JRadioButton();
        RadioNegocios = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtninos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkConferencia = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaHotel = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFacturacionTotal = new javax.swing.JTextField();
        txtVacacionesReserva = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNegociosReserva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NRO HABITACION");

        jLabel2.setText("DIAS RESERVADOS");

        jLabel3.setText("VIGENTE");

        chkVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVigenteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioVacaciones);
        radioVacaciones.setText("VACACIONES");
        radioVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVacacionesActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioNegocios);
        RadioNegocios.setText("NEGOCIOS");
        RadioNegocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNegociosActionPerformed(evt);
            }
        });

        jLabel4.setText("NIÑOS");

        jLabel5.setText("CONFERENCIA");

        jScrollPane1.setViewportView(listaHotel);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Facturación total vigente");

        jLabel7.setText("Cantidad de reservas");

        txtFacturacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturacionTotalActionPerformed(evt);
            }
        });

        txtVacacionesReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacacionesReservaActionPerformed(evt);
            }
        });

        jButton2.setText("REPORTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Vacaciones");

        jLabel9.setText("Negocios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(21, 21, 21)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkVigente)
                    .addComponent(txtReservados, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtNrohabitacion)
                    .addComponent(txtninos)
                    .addComponent(chkConferencia)
                    .addComponent(txtFacturacionTotal))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(158, 158, 158))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(radioVacaciones)
                        .addGap(30, 30, 30)
                        .addComponent(RadioNegocios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVacacionesReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtNegociosReserva))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioVacaciones)
                    .addComponent(RadioNegocios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNrohabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtReservados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(chkVigente))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtninos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(chkConferencia))
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFacturacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtVacacionesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNegociosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVigenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVigenteActionPerformed

    private void radioVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVacacionesActionPerformed
         txtninos.setEnabled(true);
         chkConferencia.setEnabled(false);        

        // TODO add your handling code here:
    }//GEN-LAST:event_radioVacacionesActionPerformed

    private void RadioNegociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNegociosActionPerformed
         txtninos.setEnabled(false);
         chkConferencia.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNegociosActionPerformed

    private void txtVacacionesReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacacionesReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacacionesReservaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int nroHabitacion = Integer.parseInt(txtNrohabitacion.getText());
    double diasReservados = Double.parseDouble(txtReservados.getText());
    boolean vigente = chkVigente.isSelected();
    
    
    if(radioVacaciones.isSelected())
    {
        int ninos = Integer.parseInt(txtninos.getText());
        Vacaciones v = new Vacaciones(nroHabitacion,diasReservados,vigente,ninos);
        hotel.AgregarReserva(v);
                
    }

    else 
    {
        boolean conferencia = chkConferencia.isSelected();
        Negocios n = new Negocios(nroHabitacion,diasReservados,vigente,conferencia);
        hotel.AgregarReserva(n);
        
    }

    listaHotel.setListData(hotel.getReservas().toArray());
    
    JOptionPane.showMessageDialog(this, "Reserva cargada con Exito : ");
    
    txtNrohabitacion.setText("");
    txtReservados.setText("");
    txtReservados.setText("");
    chkVigente.setSelected(false);
    txtninos.setText("");
    chkConferencia.setSelected(false);
    
    
    
    
    
    
    
  







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFacturacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturacionTotalActionPerformed
           




        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturacionTotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            txtFacturacionTotal.setText(String.valueOf(hotel.facturacionTotalvigente()));
            txtVacacionesReserva.setText(hotel.devolverReservaVacaciones()+"");
            txtNegociosReserva.setText(hotel.devolverReservaNegocios()+"");
            


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioNegocios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkConferencia;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaHotel;
    private javax.swing.JRadioButton radioVacaciones;
    private javax.swing.JTextField txtFacturacionTotal;
    private javax.swing.JTextField txtNegociosReserva;
    private javax.swing.JTextField txtNrohabitacion;
    private javax.swing.JTextField txtReservados;
    private javax.swing.JTextField txtVacacionesReserva;
    private javax.swing.JTextField txtninos;
    // End of variables declaration//GEN-END:variables
}
